schema = {
    "name": "makers",
    "field_type": "SINGLE_CHOICE",
    "control": "select",
    "schema": {
        "label": {"en": "Maker", "fr":"Fabriquant"},
        "options": [
            {"value": "albanese", "label": {"en":"Albanese", "fr": "Albanese"}},
            {"value": "allan-candy", "label": {"en":"Allan Candy", "fr":"Allan Candy"}},
            {"value": "mr-mallo", "label": {"en":"Mr. Mallo", "fr":"Mr. Mallo"}},
            {"value": "candytech", "label": {"en":"Candytech", "fr":"Candytech"}},
            {"value": "capco", "label": {"en":"Capco", "fr":"Capco"}},
            {"value": "concord", "label": {"en":"Concord", "fr":"Concord"}},
            {"value": "dare", "label": {"en":"Dare", "fr":"Dare"}},
            {"value": "farleys", "label": {"en":"Farley's", "fr":"Farley's"}},
            {"value": "ferrara-pan", "label": {"en":"Ferrara pan", "fr":"Ferrara pan"}},
            {"value": "au-some", "label": {"en":"Au'Some", "fr":"Au'Some"}},
            {"value": "haribo", "label": {"en":"Haribo", "fr":"Haribo"}},
            {"value": "kenny", "label": {"en":"Kenny", "fr":"Kenny"}},
            {"value": "kimmie-candy", "label": {"en":"Kimmie Candy", "fr":"Kimmie Candy"}},
            {"value": "master-foods", "label": {"en":"Master Foods", "fr":"Master Foods"}},
            {"value": "mc-cormicks", "label": {"en":"Mc Cormicks", "fr":"Mc Cormicks"}},
            {"value": "necco", "label": {"en":"Necco", "fr":"Necco"}},
            {"value": "nik-l-nip", "label": {"en":"Nik-L-Nip", "fr":"Nik-L-Nip"}},
            {"value": "oak-leaf", "label": {"en":"Oak Leaf", "fr":"Oak Leaf"}},
            {"value": "s-and-m", "label": {"en":"S&M", "fr":"S&M"}},
            {"value": "sweet-pack", "label": {"en":"Sweet Pack", "fr":"Sweet Pack"}},
            {"value": "topps", "label": {"en":"Topps", "fr":"Topps"}},
            {"value": "zachary", "label": {"en":"Zachary", "fr":"Zachary"}},
            {"value": "foleys", "label": {"en":"Foley's", "fr":"Foley's"}},
            {"value": "regal", "label": {"en":"Regal", "fr":"Regal"}},
            {"value": "candy-spain", "label": {"en":"Candy Spain", "fr":"Candy Spain"}},
            {"value": "mars", "label": {"en":"Mars", "fr":"Mars"}},
            {"value": "hershey", "label": {"en":"Hershey", "fr":"Hershey"}},
            {"value": "adams-and-brooks", "label": {"en":"Adams & Brooks", "fr":"Adams & Brooks"}},
            {"value": "wonka", "label": {"en":"Wonka", "fr":"Wonka"}},
            {"value": "autre", "label": {"en":"Other", "fr":"Autre"}},
            {"value": "arway", "label": {"en":"Arway", "fr":"Arway"}},
            {"value": "canels", "label": {"en":"Canel's", "fr":"Canel's"}},
            {"value": "primrose", "label": {"en":"Primrose", "fr":"Primrose"}},
            {"value": "sweet-work", "label": {"en":"Sweet Work", "fr":"Sweet Work"}},
            {"value": "miss-arachew", "label": {"en":"Miss Arachew", "fr":"Miss Arachew"}},
            {"value": "warrell-corporation", "label": {"en":"Warrell Corporation", "fr":"Warrell Corporation"}},
            {"value": "blommer", "label": {"en":"Blommer", "fr":"Blommer"}},
            {"value": "runk", "label": {"en":"Runk", "fr":"Runk"}},
            {"value": "test", "label": {"en":"test", "fr":"test"}},
            {"value": "sweet-maple", "label": {"en":"Sweet Maple", "fr":"Sweet Maple"}},
            {"value": "rito", "label": {"en":"Rito", "fr":"Rito"}},
            {"value": "exclusive-candy", "label": {"en":"Exclusive candy", "fr":"Exclusive candy"}},
            {"value": "impact", "label": {"en":"Impact", "fr":"Impact"}},
            {"value": "wrigley", "label": {"en":"Wrigley", "fr":"Wrigley"}},
            {"value": "huer", "label": {"en":"Huer", "fr":"Huer"}},
            {"value": "brachs", "label": {"en":"Brach's", "fr":"Brach's"}},
            {"value": "one-better", "label": {"en":"One better", "fr":"One better"}},
            {"value": "triova", "label": {"en":"Triova", "fr":"Triova"}}
        ]
    }
}
